### PR TITLE
Better error messages for styles; better docs

### LINKED ISSUE #290: Source style files the same way as .mdlrc files
## Description

At present it appears that`.mdlrc` files are sourced by walking up the directory tree from the current working directory, the directory where `mdl` was invoked, stopping at the user's home directory and uses the first `.mdlrc` file it finds on the way (#111). It appears that a style file  specified in `.mdlrc` is not sourced in the same manner, that `mdl` looks only in the current working directory and halts with a cryptic error message when it can't find it. This leads to `mdl` functioning in some directories and malfunctioning in others.

Edit: remove misleading and irrelevant filename.

### Environment

macOS 10.14 Mojave, which has ruby 2.3.7p456 as the system-installed version.

**MDL Version:** 0.5.0

### Expected Behaviour

`mdl` succeeds when the style file specified by filename only in a `.mdlrc` exists within in the directory hierarchy from the current working directory to the user's home directory, falling back to the default location(s). If the specified file can not be found `mdl` should either display a warning and continue or display a meaningful error and halt.

It will probably be beneficial to split relative file searches into two cases:

1. style file specified by filename only, i.e. specified style file does not contain `/` and does end in `.rb`, and
1. style file specified by relative path, i.e. specified style contains `/` and ends in `.rb`.

In case (1) it makes sense to walk the hierarchy starting from the current working directory, while in case (2) it makes more sense to just look relative to the location of the `.mdlrc` file.

### Actual Behaviour

`mdl` succeeds when the style file specified by relative path in `.mdlrc` exists relative to the current working directory but fails when invoked, for example, one level down

```shell
$ cd subdirectory
$ mdl *.md
~/.gem/ruby/2.3.0/gems/mdl-0.5.0/lib/mdl/style.rb:51:in `read': No such file or directory @ rb_sysopen - .mdlstyle.rb (Errno::ENOENT)
	from ~/.gem/ruby/2.3.0/gems/mdl-0.5.0/lib/mdl/style.rb:51:in `load'
	from ~/.gem/ruby/2.3.0/gems/mdl-0.5.0/lib/mdl.rb:26:in `run'
	from ~/.gem/ruby/2.3.0/gems/mdl-0.5.0/bin/mdl:10:in `<top (required)>'
	from ~/.gem/ruby/2.3.0/bin/mdl:22:in `load'
	from ~/.gem/ruby/2.3.0/bin/mdl:22:in `<main>'
```

## Replication Case

The following replicates the error:

```shell
mkdir -p mdlbugtest/subdirectory
cd mdlbugtest/
echo 'style ".mdlstyle.rb"' > .mdlrc
touch .mdlstyle.rb
touch subdirectory/somefile.md
mdl subdirectory/somefile.md
cd subdirectory/
mdl somefile.md
```

### PR DESCRIPTION
**Pull request by jaymzh**
This makes it clear to the user what went wrong and why:

```
$ ./bin/mdl -s 'test'
test does not appear to be a build-in style. If you meant to pass in your own style file, it must contain a '/' or end in '.rb'. See https://github.com/markdownlint/markdownlint/blob/master/docs/configuration.md
```

```
$ ./bin/mdl -s test.rb
Style 'test.rb' does not exist.
```

## Description
We didn't have a good error message, now we do.

## Related Issues
Closes #290

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation (non-breaking change that does not add functionality but updates documentation)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:
- [X] I have read the [**CONTRIBUTING**](https://github.com/markdownlint/markdownlint/blob/master/CONTRIBUTING.md) document.
- [X] Wrote [good commit messages](https://chris.beams.io/posts/git-commit/)
- [X] Feature branch is up-to-date with `master`, if not - rebase it
- [ ] Added tests for all new/changed functionality, including tests for positive and negative scenarios
- [X] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences

### CODE REVIEW

File: lib/mdl/style.rb [hunk 1]
```diff
@@ -50,9 +50,23 @@ def exclude_tag(t)
     end
 
     def self.load(style_file, rules)
-      unless style_file.include?("/") or style_file.end_with?(".rb")
-        style_file = File.expand_path("../styles/#{style_file}.rb", __FILE__)
+      unless style_file.include?("/") || style_file.end_with?(".rb")
+        tmp = File.expand_path("../styles/#{style_file}.rb", __FILE__)
+        unless File.exist?(tmp)
+          STDERR.puts "#{style_file} does not appear to be a build-in style." +
```
Comment (grantneufeld) [inline lib/mdl/style.rb]:
```suggestion
          STDERR.puts "#{style_file} does not appear to be a built-in style." +
```

**Review by NaomiReeves — APPROVED** [review]
